name: oye_taxi_v2
description: _____________

# > Task :app:signingReport
#Variant: debugUnitTest
#Config: debug
#Store: C:\Users\Lenovo\.android\debug.keystore
#Alias: AndroidDebugKey
#MD5: BD:2F:AA:B9:60:53:F5:13:31:98:43:0E:F0:29:66:1D
#SHA1: EF:33:AC:63:36:20:EB:38:04:B5:6D:8A:2C:85:A2:13:A3:AC:2B:C4
#SHA-256: 3E:DF:5B:81:D6:D9:2B:76:DB:DE:32:A3:54:02:FA:15:64:6D:4A:19:9A:AD:93:63:00:15:7C:EE:CD:55:4C:58
#Valid until: Tuesday, 16 June, 2048
#----------
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.15
  cloud_firestore: ^0.9.0
  #firebase_auth: ^0.8.4+5
  #firebase_core: ^0.3.0
  rxdart: any
  geoflutterfire:
  location: ^2.3.5
  #google_maps_webservice: ^0.0.14
  flutter_google_places:
  geolocator: any
  http:
  google_places_picker:
  loading_card:
  percent_indicator:
  expandable_bottom_bar: ^0.1.1
  expandable_card: ^0.0.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - taxi.png
    - car.png
    - book.png
    - one_tip.png
    - onep.png
    - threep.png
    - ic_user.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
